/** English UI strings aligned with classic `en-us.js` (profile, welcome, achievements). */
export const S = {
  welcomeBadge: 'The Giveaways Club presents',
  welcomeTagline: 'Classic brick-breaking. Online scores. Achievements that bite back.',
  welcomeHook: 'Pick your callsign and step into the neon lane.',
  welcomeUsernameLabel: 'Your callsign',
  welcomePlaceholder: 'e.g. StarPilot',
  welcomePlay: 'Play now',
  welcomeErrLen: 'Use 2–24 characters.',
  welcomeErrChars: 'Letters, numbers, spaces, _ and - only (accented letters allowed).',
  profileHeader: 'Profile',
  tabProfile: 'Profile',
  tabLeaderboard: 'Leaderboard',
  statPlaytime: 'Time played (all sessions)',
  statTotalPoints: 'Total points (lifetime)',
  statBestRun: 'Best run (single life)',
  statDeaths: 'Game overs',
  statLevels: 'Levels unlocked',
  profileCloudOn: 'Cloud connected — stats and achievements sync to the server while you play.',
  profileCloudOff: 'Local save only. Run the API server (npm start) for cloud sync.',
  copyLink: 'Copy invite link',
  syncNow: 'Sync now',
  logout: 'Log out',
  logoutConfirm: 'Log out of this device? You can sign in again with your player name.',
  achievementsHeading: 'Achievements',
  achToastUnlocked: 'Achievement unlocked',
  shareBlurb: 'Come play TGC-Arkade with me!',
  copyManual: 'Copy this link:',
  lbPlayer: 'Player',
  lbScore: 'Best session',
  lbUpdated: 'Updated',
  lbError: 'Could not load ranking.',
  lbEmpty: 'No scores yet.',
  achLvlTitle: 'Level {n} conquered',
  achLvlDesc: 'You cleared level {n}. Keep going!',
} as const;

export const ACH_TITLES: Record<string, string> = {
  cadet_joined: 'Cadet on board',
  tgc_legend: 'TGC legend',
  point_collector_10k: 'Point collector',
  point_hoarder_50k: 'Point hoarder',
  score_ninja_100k: 'Score ninja',
  oops_first_death: 'Oops, gravity wins',
  rubber_ball_10: 'Rubber soul',
  cosmic_persistence_50: 'Cosmic persistence',
  coffee_break_10m: 'Coffee break hero',
  marathon_1h: 'Hour-long hero',
  lightning_round: 'Lightning round',
  full_health_win: 'Full hearts club',
};

export const ACH_DESCS: Record<string, string> = {
  cadet_joined: 'You picked a callsign. The arcade now knows who you are.',
  tgc_legend: 'You cleared every level in Space. Take a bow.',
  point_collector_10k: '10,000 points in a single run. Cha-ching!',
  point_hoarder_50k: '50,000 points. The scoreboard needs a wider screen.',
  score_ninja_100k: '100,000 points. Legends will pixelate your name.',
  oops_first_death: 'First game over. The ball was rude; you were brave.',
  rubber_ball_10: '10 game overs. You bounce back like a pro.',
  cosmic_persistence_50: '50 game overs. The universe respects stubborn.',
  coffee_break_10m: '10 minutes of playtime. Hydration optional.',
  marathon_1h: 'One hour in the arcade. Stretch those wrists!',
  lightning_round: 'Cleared a level in under 45 seconds. Blink and you miss it.',
  full_health_win: 'Won a round without losing a life. Cool, calm, brickless.',
};
